BackEndProject/Areas/Admin/Controllers/BlogAdminController.cs
using BackEndProject.DAL;
using BackEndProject.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BackEndProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BlogAdminController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;
        public BlogAdminController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public IActionResult Index()
        {
            List<Blog> blogs = _context.Blogs.Include(b => b.BlogDetail).ToList();
            return View(blogs);
        }
        public IActionResult Create()
        {
            return View();
        }
    }
}

BackEndProject/Areas/Admin/Views/BlogAdmin/Create.cshtml
@model Blog
@{
    ViewData["Title"] = "Create";
}
<div class="row">
    <div class="col-12 grid-margin stretch-card">
        <div class="card ">
            <div class="card-body">
                <h4 class="card-title">Blog Create</h4>
                <div class="text-danger" asp-validation-summary="ModelOnly"></div>
                <form class="forms-sample" method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label asp-for="Photo"></label>
                        <input asp-for="Photo" class="form-control" placeholder="Photo" accept="image/*">
                        <span class="text-danger" asp-validation-for="Photo"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Tittle"></label>
                        <input asp-for="Tittle" class="form-control" placeholder="Tittle">
                        <span class="text-danger" asp-validation-for="Tittle"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="BlogDetail.Description"></label>
                        <textarea asp-for="BlogDetail.Description" id="#editor"></textarea>
                    </div>
                    <div class="form-group">
                        <label asp-for="Posted"></label>
                        <input asp-for="Posted" class="form-control" placeholder="Posted">
                        <span class="text-danger" asp-validation-for="Posted"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Author"></label>
                        <input asp-for="Author" class="form-control" placeholder="Author">
                        <span class="text-danger" asp-validation-for="Author"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Comment"></label>
                        <input asp-for="Comment" class="form-control" placeholder="Comment">
                        <span class="text-danger" asp-validation-for="Comment"></span>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <a class="btn btn-light" asp-action="Index">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>
@section Script{
    <script src="https://cdn.ckeditor.com/ckeditor5/27.1.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#editor'))
            .catch(error => {
                console.error(error);
            });
    </script>
    <partial name="_ValidationPartial" />

}

BackEndProject/Areas/Admin/Views/BlogAdmin/Index.cshtml
@model List<Blog>
@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card ">
        <div class="card ">
            <div class="card-body ">
                <h4 class="card-title">Events</h4>
                <a asp-controller="BlogAdmin" asp-action="Create" class="btn btn-success">Create</a>
                <div class="table-responsive">
                    <table class="table table-striped ">
                        <thead>
                            <tr>
                                <th>
                                    Image
                                </th>
                                <th>
                                    Tittle
                                </th>
                                <th>
                                    Description
                                </th>
                                <th>
                                    Posted
                                </th>
                                <th>
                                    Auther
                                </th>
                                <th>
                                    IsDeleted
                                </th>
                                <th>
                                    Settings
                                </th>

                            </tr>

                        </thead>
                        <tbody>
                            @foreach (Blog b in Model)
                            {
                                <tr>
                                    <td>
                                        <img style="width: 100px; height: 100px; object-fit:cover" src="~/img/blog/@b.İmageUrl" a />
                                    </td>
                                    <td>
                                        @b.Tittle
                                    </td>

                                    <td>
                                        <!-- Button trigger modal -->
                                        <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#blog-@b.Id">
                                            Description
                                        </button>

                                        <!-- Modal -->
                                        <div class="modal fade" id="blog-@b.Id" tabindex="-1" role="dialog" aria-labelledby="blog-@b.Id" aria-hidden="true">
                                            <div class="modal-dialog modal-dialog-centered" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">
                                                        @Html.Raw(b.BlogDetail.Description);
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                        <button type="button" class="btn btn-primary">Save changes</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        @b.Posted.ToString("D")
                                    </td>
                                    <td class="text-behance">
                                        @b.Author
                                    </td>

                                    @if (b.IsDeleted)
                                    {
                                        <td class="text-danger">
                                            Deactive
                                        </td>

                                    }
                                    else
                                    {
                                        <td class="text-success">
                                            Active
                                        </td>
                                    }
                                    <td>
                                        <a class="btn btn-warning" asp-action="Update" asp-route-id="@b.Id">
                                            Edit
                                        </a>
                                        @if (b.IsDeleted)
                                        {
                                            <a class="btn btn-success" asp-action="Activity" asp-route-id="@b.Id">
                                                Activated
                                            </a>
                                        }
                                        else
                                        {
                                            <a class="btn btn-danger" asp-action="Activity" asp-route-id="@b.Id">
                                                Deactivated
                                            </a>
                                        }

                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>