BackEndProject/Areas/Admin/Controllers/SocialMediaController.cs
using BackEndProject.DAL;
using BackEndProject.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BackEndProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SocialMediaController : Controller
    {

        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;
        public SocialMediaController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public IActionResult Index()
        {
            List<Teacher> teachers = _context.Teachers.Include(t => t.Socials).ToList();
            return View(teachers);
        }
        public IActionResult Create()
        {
            ViewBag.TeacherList = _context.Teachers.ToList();
            return View();
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Create(Social social)
        {
            ViewBag.TeacherList = _context.Teachers.ToList();
            if (!ModelState.IsValid) return View();
            await _context.Socials.AddAsync(social);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

BackEndProject/Areas/Admin/Views/SocialMedia/Create.cshtml
@model Social
@{
    ViewData["Title"] = "Create";
}

<div class="row">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Create Course</h4>
                <div class="text-danger" asp-validation-summary="ModelOnly"></div>
                <form class="forms-sample" method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label asp-for="Link">Select Images:</label>
                        <input asp-for="Link" class="form-control" accept="image/*">
                        <span class="text-danger" asp-validation-for="Link"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Icon">Crate Product</label>
                        <input asp-for="Icon" class="form-control" placeholder="Name">
                        <span class="text-danger" asp-validation-for="Icon"></span>
                    </div>
                    <div class="form-group">
                        <label for="Teachers">Select Teacher</label>
                        <select class="form-control" asp-for="TeacherId">
                            <option>All Teachers</option>
                            @foreach (Teacher tc in ViewBag.TeacherList)
                            {
                                <option value="@tc.Id">@tc.FullName</option>
                            }
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <a class="btn btn-light" asp-action="Index">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>
@section Script{
    <script src="https://cdn.ckeditor.com/ckeditor5/27.1.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#editor'))
            .catch(error => {
                console.error(error);
            });
    </script>
    <partial name="_ValidationPartial" />

}

BackEndProject/Areas/Admin/Views/SocialMedia/Index.cshtml
@model List<Teacher>
@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card ">
        <div class="card ">
            <div class="card-body ">
                <h4 class="card-title">Teachers</h4>
                <a asp-controller="SocialMedia" asp-action="Create" class="btn btn-success">Create</a>
                <div class="table-responsive">
                    <table class="table table-striped ">
                        <thead>
                            <tr>
                                <th>
                                    Image
                                </th>
                                <th>
                                    Fullname
                                </th>
                                <th>
                                    Icons
                                </th>

                            </tr>

                        </thead>
                        <tbody>
                            @foreach (Teacher t in Model)
                            {
                                <tr>
                                    <td>
                                        <img style="width: 100px; height: 100px; object-fit:cover" src="~/img/teacher/@t.ImageUrl" a />
                                    </td>
                                    <td>
                                        @t.FullName
                                    </td>
                                    <td>
                                            <!-- Button trigger modal -->
                                            <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#speaker-@t.Id">
                                                Icons
                                            </button>


                                            <!-- Modal -->
                                            <div class="modal fade" id="speaker-@t.Id" tabindex="-1" role="dialog" aria-labelledby="speaker-@t.Id" aria-hidden="true">
                                                <div class="modal-dialog modal-dialog-centered" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                <span aria-hidden="true">&times;</span>
                                                            </button>
                                                        </div>
                                                        <div class="modal-body">
                                                           
                                                                @foreach (Social tc in t.Socials)
                                                                {
                                                                    <a class="icon-asd" href="@tc.Link"><i class="@tc.Icon"></i></a>
                                                                }

                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                            <button type="button" class="btn btn-primary">Save changes</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>