BackEndProject/Areas/Admin/Controllers/EventAdminController.cs
using BackEndProject.DAL;
using BackEndProject.Extentions;
using BackEndProject.Models;
using BackEndProject.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BackEndProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class EventAdminController : Controller
    {

        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;
        public EventAdminController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public IActionResult Index()
        {
            List<Event> Event = _context.Events.Include(e => e.EventDetail).Include(e => e.EventSpeakers).ThenInclude(e => e.Speaker).ToList();
            return View(Event);
        }
        public IActionResult Detail(int? id)
        {
            if (id == null) return NotFound();
            Event Event = _context.Events.Include(e => e.EventDetail).Include(e => e.EventSpeakers).ThenInclude(es => es.Speaker).FirstOrDefault(e => e.Id == id);
            if (Event == null) return NotFound();

            return View(Event);
        }
        public IActionResult Create()
        {
            ViewBag.Speakers = _context.Speakers.ToList();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EventVM eventVM)
        {
            ViewBag.Speakers = _context.Speakers.ToList();


            if (!ModelState.IsValid) return View();

            if (eventVM.Event.Photo == null)
            {
                ModelState.AddModelError("Event.Photo", "Please select Photo");
                return View();
            }
            if (!eventVM.Event.Photo.IsValidType("image/"))
            {
                ModelState.AddModelError("Event.Photo", "Please select image Type");
                return View();
            }
            if (!eventVM.Event.Photo.IsValidSize(300))
            {
                ModelState.AddModelError("Event.Photo", "Please select image Size less than kb");
                return View();
            }
            if (eventVM.Speakers == null)
            {
                ModelState.AddModelError("Speakers", "Please Select Speakers");
                return View();
            }
            string path = Path.Combine("img", "event");
            eventVM.Event.ImageUrl = await eventVM.Event.Photo.SaveFileAsync(_env.WebRootPath, path);

            await _context.Events.AddAsync(eventVM.Event);
            await _context.SaveChangesAsync();


            eventVM.EventDetail.EventId = eventVM.Event.Id;




            List<EventSpeaker> eventSpeakers = new List<EventSpeaker>();
            EventSpeaker eventSpeaker = new EventSpeaker();
            eventSpeaker.EventId = eventVM.Event.Id;
            foreach (int sp in eventVM.Speakers)
            {
                eventSpeaker.SpeakerId = sp;
                eventSpeakers.Add(eventSpeaker);
            }

            eventVM.Event.EventSpeakers = eventSpeakers;

            _context.Update(eventVM.Event);


            await _context.EventDetails.AddAsync(eventVM.EventDetail);
            await _context.SaveChangesAsync();


            return RedirectToAction(nameof(Index));
        }

        public IActionResult Update(int? id)
        {
            ViewBag.Speakers = _context.Speakers.ToList();
            if (id == null) return NotFound();
            Event DbEvent = _context.Events.Include(e => e.EventDetail).Include(e => e.EventSpeakers).
                ThenInclude(es => es.Speaker).FirstOrDefault(e => e.Id == id);
            if (DbEvent == null) return NotFound();
            List<Speaker> speakers = new List<Speaker>();
            foreach (EventSpeaker es in DbEvent.EventSpeakers)
            {
                speakers.Add(es.Speaker);
            }

            EventVM eventVM = new EventVM
            {
                Event = DbEvent,
                EventDetail = DbEvent.EventDetail,
                SpekarsModels = speakers

            };
            return View(eventVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int? id, EventVM eventVM)
        {
            ViewBag.Speakers = _context.Speakers.ToList();
            if (id == null) return NotFound();
            Event DbEvent = _context.Events.Include(e => e.EventDetail).Include(e => e.EventSpeakers).
                ThenInclude(es => es.Speaker).FirstOrDefault(e => e.Id == id);
            if (!ModelState.IsValid) return View(DbEvent);

            if (eventVM.Event.Photo == null)
            {
                ModelState.AddModelError("Event.Photo", "Please select Photo");
                return View(DbEvent);
            }
            if (!eventVM.Event.Photo.IsValidType("image/"))
            {
                ModelState.AddModelError("Event.Photo", "Please select image Type");
                return View(DbEvent);
            }
            if (!eventVM.Event.Photo.IsValidSize(300))
            {
                ModelState.AddModelError("Event.Photo", "Please select image Size less than kb");
                return View(DbEvent);
            }
            if (eventVM.Speakers == null)
            {
                ModelState.AddModelError("Speakers", "Please Select Speakers");
                return View();
            }
            string path = Path.Combine("img", "event");
            eventVM.Event.ImageUrl = await eventVM.Event.Photo.SaveFileAsync(_env.WebRootPath, path);

            foreach (EventSpeaker s in DbEvent.EventSpeakers)
            {
                _context.EventSpeakers.Remove(s);
            }
            List<EventSpeaker> eventSpeakers = new List<EventSpeaker>();
            EventSpeaker eventSpeaker = new EventSpeaker();
            eventSpeaker.EventId = DbEvent.Id;
            foreach (int sp in eventVM.Speakers)
            {
                eventSpeaker.SpeakerId = sp;
                eventSpeakers.Add(eventSpeaker);
            }

            DbEvent = eventVM.Event;
            DbEvent.EventDetail = eventVM.EventDetail;
            DbEvent.EventSpeakers = eventSpeakers;

            _context.Update(DbEvent);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

BackEndProject/Areas/Admin/Views/EventAdmin/Create.cshtml
@model Event
@{
    ViewData["Title"] = "Create";
}

<div class="row">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Create Course</h4>
                <div class="text-danger" asp-validation-summary="ModelOnly"></div>
                <form class="forms-sample" method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label asp-for="Photo">Select Images:</label>
                        <input asp-for="Photo" class="form-control" accept="image/*">
                        <span class="text-danger" asp-validation-for="Photo"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Lesson">Crate Product</label>
                        <input asp-for="Lesson" class="form-control" placeholder="Name">
                        <span class="text-danger" asp-validation-for="Lesson"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="EventTime">Description</label>
                        <input asp-for="EventTime" class="form-control" placeholder="Description">
                        <span class="text-danger" asp-validation-for="EventTime"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="EventEndTime">Description</label>
                        <input asp-for="EventEndTime" class="form-control" placeholder="Description">
                        <span class="text-danger" asp-validation-for="EventEndTime"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Venue">Description</label>
                        <input asp-for="Venue" class="form-control" placeholder="Venue">
                        <span class="text-danger" asp-validation-for="Venue"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="EventDetail.ExactLocation">Description</label>
                        <input asp-for="EventDetail.ExactLocation" class="form-control" placeholder="ExactLocation">
                        <span class="text-danger" asp-validation-for="EventDetail.ExactLocation"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="EventDetail.Description">Description</label>
                        <input asp-for="EventDetail.Description" class="form-control" placeholder="Description">
                        <span class="text-danger" asp-validation-for="EventDetail.Description"></span>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <a class="btn btn-light" asp-action="Index">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>
@section Script{
    <script src="https://cdn.ckeditor.com/ckeditor5/27.1.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#editor'))
            .catch(error => {
                console.error(error);
            });
    </script>
    <partial name="_ValidationPartial" />

}

BackEndProject/Areas/Admin/Views/EventAdmin/Detail.cshtml
@model Event
@{
    ViewData["Title"] = "Detail";
}

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Course</h4>
                <a asp-controller="EventAdmin" asp-action="Index" class="btn btn-secondary">Go Back</a>
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>
                                    Image
                                </th>
                                <th>
                                    Description
                                </th>
                                <th>
                                    Event
                                </th>
                                <th>
                                    Time
                                </th>
                                <th>
                                    Venue
                                </th>

                                <th>
                                    Speakers
                                </th>
                                <th>
                                    Settings
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    <img src="~/img/event/@Model.ImageUrl" style="width:120px; height:115px; object-fit:cover" />
                                </td>
                                <td>
                                    <!-- Button trigger modal -->
                                    <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#exampleModalLong">
                                        Click for Description
                                    </button>

                                    <!-- Modal -->
                                    <div class="modal fade" id="#exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="#exampleModalLong" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    @Html.Raw(Model.EventDetail.Description)
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                    <button type="button" class="btn btn-primary">Save changes</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <h5>
                                        @Model.Lesson
                                    </h5>
                                </td>
                                <td>
                                    <h5> @Model.EventTime.ToString("dd") @Model.EventTime.ToString("MMM") @Model.EventTime.ToString("t") - @Model.EventEndTime.ToString("t")</h5>

                                </td>
                                <td>
                                    <!-- Button trigger modal -->
                                    <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#exampleModalCenter">
                                        Click for Venue
                                    </button>

                                    <!-- Modal -->
                                    <div class="modal fade" id="#exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="#exampleModalCenter" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    @Model.Venue @Model.EventDetail.ExactLocation
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                    <button type="button" class="btn btn-primary">Save changes</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <!-- Button trigger modal -->
                                    <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#speaker-@Model.Id">
                                        Click for Speakers
                                    </button>

                                    <!-- Modal -->
                                    <div class="modal fade" id="speaker-@Model.Id" tabindex="-1" role="dialog" aria-labelledby="speaker-@Model.Id" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    @foreach (EventSpeaker es in Model.EventSpeakers)
                                                    {
                                                        <div class="row mt-5">
                                                            <div class="col-6">
                                                                @Html.Raw("<p>Speaker Name</p>")
                                                                <h3>@es.Speaker.Fullname</h3>
                                                                @Html.Raw("<p>Speaker Occupation</p>")
                                                                <h3>@es.Speaker.Occupation</h3>
                                                            </div>
                                                            <div class="col-6">
                                                                <img style="width: 140px; height: 140px; object-fit:cover" src="~/img/event/@es.Speaker.ImageUrl" a />
                                                            </div>
                                                        </div>
                                                    }
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                    <button type="button" class="btn btn-primary">Save changes</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <a class="btn btn-warning" asp-action="Update" asp-route-id="@Model.Id">
                                        Edit
                                    </a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

BackEndProject/Areas/Admin/Views/EventAdmin/Index.cshtml
@model List<Event>
@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Course</h4>
                <a asp-controller="EventAdmin" asp-action="Create" class="btn btn-success">Create</a>
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>
                                    Image
                                </th>
                                <th>
                                    Event
                                </th>
                                <th>
                                    Time
                                </th>
                                <th>
                                    Venue
                                </th>
                                <th>
                                    Spikers Name
                                </th>

                                <th>
                                    Active
                                </th>
                                <th>
                                    Settings
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (Event ev in Model)
                            {

                            <tr>
                                <td>
                                    <img src="~/img/event/@ev.ImageUrl" style="width:120px; height:115px; object-fit:cover" />
                                </td>
                                <td>
                                    @ev.Lesson
                                </td>
                                <td>
                                    @ev.EventTime.ToString("dd") @ev.EventTime.ToString("MM") @ev.EventTime.ToString("t")-@ev.EventTime.ToString("t")
                                </td>
                                <td>
                                    @ev.Venue
                                </td>
                                <td>
                                    <!-- Button trigger modal -->
                                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#speaker-@ev.Id">
                                        Launch demo modal
                                    </button>

                                    <!-- Modal -->
                                    <div class="modal fade" id="speaker-@ev.Id" tabindex="-1" role="dialog" aria-labelledby="speaker-@ev.Id" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">

                                                    @foreach (EventSpeaker es in ev.EventSpeakers)
                                                    {
                                                       <div class="row mt-4">
                                                           <div class="col-6">
                                                               @Html.Raw("Speaker Name")
                                                               <h5>@es.Speaker.Fullname</h5>
                                                               @Html.Raw("Speaker Ocupation")
                                                               <h5>@es.Speaker.Occupation</h5>
                                                           </div>
                                                           <div class="col-6">
                                                               <img src="~/img/event/@es.Speaker.ImageUrl" style="width:120px; height:115px; object-fit:cover" />
                                                           </div>
                                                       </div>
                                                       
                                                    }
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                    <button type="button" class="btn btn-primary">Save changes</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                @if (ev.IsDeleted)
                                {
                                    <td class="text-success">
                                        Active
                                    </td>
                                }
                                else
                                {

                                    <td class="text-danger">
                                        Deactive
                                    </td>

                                }
                                <td>
                                    <a class="btn btn-info" asp-action="Detail" asp-route-id="@ev.Id">
                                        <i class="mdi mdi-account-card-details"></i>
                                    </a>
                                    <a class="btn btn-warning" asp-action="Update" asp-route-id="@ev.Id">

                                        <i class="mdi mdi-table-edit"></i>
                                    </a>
                                    @if (ev.IsDeleted)
                                    {
                                        <a class="btn btn-danger" asp-action="Activity" asp-route-id="@ev.Id">
                                            <i class="mdi mdi-delete-sweep"></i>
                                        </a>
                                    }
                                    else
                                    {
                                        <a class="btn btn-success" asp-action="Activity" asp-route-id="@ev.Id">
                                            <i class="mdi mdi-delete-sweep"></i>
                                        </a>
                                    }

                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>