BackEndProject/Areas/Admin/Controllers/CourseAdminController.cs
using BackEndProject.DAL;
using BackEndProject.Extentions;
using BackEndProject.Helpers;
using BackEndProject.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BackEndProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CourseAdminController : Controller
    {
        
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;
        public CourseAdminController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public IActionResult Index()
        {
            List<Course> courses = _context.Courses.Include(c => c.DetailCourse).ToList();
            return View(courses);
        }
        public IActionResult Detail(int? id)
        {
            if (id == null) return NotFound();
            List<Course> courses = _context.Courses.Where(c => c.IsDeleted == false).Include(c => c.DetailCourse).ToList();
            if (courses == null) return NotFound();
            return View(courses);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Course course)
        {
            if (!ModelState.IsValid) return View();
  
            if (!course.Photo.IsValidType("image/"))
            {
                ModelState.AddModelError("Photo", "Please select photo");
            }
            if (!course.Photo.IsValidSize(300))
            {
                ModelState.AddModelError("Photo", "Please Choose the right size");
            }
            string folder = Path.Combine("img", "course");
            course.ImageUrl = await course.Photo.SaveFileAsync(_env.WebRootPath, folder);
            course.DetailCourse.Course = course;
            course.DetailCourse.CourseId = course.Id;

            await _context.AddRangeAsync(course,course.DetailCourse);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();
            Course course = await _context.Courses.FirstOrDefaultAsync(c => c.Id == id);
            if (course == null) return NotFound();
            if (!course.IsDeleted)
            {
                course.IsDeleted = true;

            }
            else
            {
                course.IsDeleted = false;

            }
            _context.Courses.Update(course);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Update(int? id)
        {
            if (id == null) return NotFound();
            Course course = _context.Courses.Include(c => c.DetailCourse).FirstOrDefault(c => c.Id == id);
            if (course == null) return NotFound();
            return View(course);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int? id, Course course)
        {
            if (id == null) return NotFound();
            Course CourseServer = _context.Courses.Include(c => c.DetailCourse).FirstOrDefault(c => c.Id == id);
            if (CourseServer == null) return NotFound();


            if (!ModelState.IsValid) return View(CourseServer);
            if (!course.Photo.IsValidType("image/"))
            {
                ModelState.AddModelError("Photo", "Please select image Type");
                return View(CourseServer);
            }
            if (!course.Photo.IsValidSize(300))
            {
                ModelState.AddModelError("Photo", "Please select image Size less than kb");
                return View(CourseServer);
            }
            string path = Path.Combine("img", "course");
            Helper.DeletedFile(_env.WebRootPath, path, CourseServer.ImageUrl);
            path = Path.Combine("img", "course");
            CourseServer.ImageUrl = await course.Photo.SaveFileAsync(_env.WebRootPath, path);
            CourseServer.Name = course.Name;
            CourseServer.Description = course.Description;
            CourseServer.DetailCourse.AboutCourse = course.DetailCourse.AboutCourse;
            CourseServer.DetailCourse.HowToApply = course.DetailCourse.HowToApply;
            CourseServer.DetailCourse.Certifcation  = course.DetailCourse.Certifcation;
            CourseServer.DetailCourse.Starts = course.DetailCourse.Starts;
            CourseServer.DetailCourse.Duration = course.DetailCourse.Duration;
            CourseServer.DetailCourse.ClassDuration = course.DetailCourse.ClassDuration;
            CourseServer.DetailCourse.SkilLevel = course.DetailCourse.SkilLevel;
            CourseServer.DetailCourse.Language = course.DetailCourse.Language;
            CourseServer.DetailCourse.Students = course.DetailCourse.Students;
            CourseServer.DetailCourse.Assesment = course.DetailCourse.Assesment;
            CourseServer.DetailCourse.Price = course.DetailCourse.Price;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

BackEndProject/Areas/Admin/Views/CourseAdmin/Create.cshtml
@model Course
@{
    ViewData["Title"] = "Create";
}

<div class="row">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Create Course</h4>
                <div class="text-danger" asp-validation-summary="ModelOnly"></div>
                <form class="forms-sample" method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label asp-for="@Model.Photo">Select Images:</label>
                        <input asp-for="@Model.Photo" class="form-control" accept="image/*">
                        <span class="text-danger" asp-validation-for="@Model.Photo"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.Name">Crate Product</label>
                        <input asp-for="@Model.Name" class="form-control" placeholder="Name">
                        <span class="text-danger" asp-validation-for="@Model.Name"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.Description">Description</label>
                        <input asp-for="@Model.Description" class="form-control" placeholder="Description">
                        <span class="text-danger" asp-validation-for="@Model.Description"></span>
                    </div>
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModalLong">
                        Click for Detail
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">

                                    <div class="form-group">
                                        <label asp-for="@Model.DetailCourse.AboutCourse">about course</label>
                                        <input asp-for="@Model.DetailCourse.AboutCourse" class="form-control" placeholder="about course">
                                        <span class="text-danger" asp-validation-for="@Model.DetailCourse.AboutCourse"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="@Model.DetailCourse.HowToApply">how to apply</label>
                                        <input asp-for="@Model.DetailCourse.HowToApply" class="form-control" placeholder="how to apply">
                                        <span class="text-danger" asp-validation-for="@Model.DetailCourse.HowToApply"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="@Model.DetailCourse.Certifcation">certification</label>
                                        <input asp-for="@Model.DetailCourse.Certifcation" class="form-control" placeholder="certification">
                                        <span class="text-danger" asp-validation-for="@Model.DetailCourse.Certifcation"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="@Model.DetailCourse.Starts">starts </label>
                                        <input asp-for="@Model.DetailCourse.Starts" id="editor" class="form-control" placeholder="starts ">
                                    </div>


                                    <div class="form-group">
                                        <label asp-for="@Model.DetailCourse.Duration">duration</label>
                                        <input asp-for="@Model.DetailCourse.Duration" class="form-control" placeholder="duration">
                                        <span class="text-danger" asp-validation-for="@Model.DetailCourse.Duration"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="@Model.DetailCourse.ClassDuration">class duration</label>
                                        <input asp-for="@Model.DetailCourse.ClassDuration" class="form-control" placeholder="class duration">
                                        <span class="text-danger" asp-validation-for="@Model.DetailCourse.ClassDuration"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="@Model.DetailCourse.SkilLevel">skill level</label>
                                        <input asp-for="@Model.DetailCourse.SkilLevel" class="form-control" placeholder="skill level">
                                        <span class="text-danger" asp-validation-for="@Model.DetailCourse.SkilLevel"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="@Model.DetailCourse.Language">language</label>
                                        <input asp-for="@Model.DetailCourse.Language" class="form-control" placeholder="language">
                                        <span class="text-danger" asp-validation-for="@Model.DetailCourse.Language"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="@Model.DetailCourse.Students">students </label>
                                        <input asp-for="@Model.DetailCourse.Students" class="form-control" placeholder="students ">
                                        <span class="text-danger" asp-validation-for="@Model.DetailCourse.Students"></span>
                                    </div>

                                    <div class="form-group">
                                        <label asp-for="@Model.DetailCourse.Assesment">assesments</label>
                                        <input asp-for="@Model.DetailCourse.Assesment" class="form-control" placeholder="assesments">
                                        <span class="text-danger" asp-validation-for="@Model.DetailCourse.Assesment"></span>
                                    </div>

                                    <div class="form-group">
                                        <label asp-for="@Model.DetailCourse.Price">course fee $</label>
                                        <input asp-for="@Model.DetailCourse.Price" class="form-control" placeholder="course fee $">
                                        <span class="text-danger" asp-validation-for="@Model.DetailCourse.Price"></span>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <button type="button" class="btn btn-primary">Save changes</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <a class="btn btn-light" asp-action="Index">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>
@section Script{
    <script src="https://cdn.ckeditor.com/ckeditor5/27.1.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#editor'))
            .catch(error => {
                console.error(error);
            });
    </script>
    <partial name="_ValidationPartial" />

}

BackEndProject/Areas/Admin/Views/CourseAdmin/Detail.cshtml
@model Course
@{
    ViewData["Title"] = "Detail";
}
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card ">
            <div class="card-body">
                <a asp-controller="CourseAdmin" asp-action="Index" class="btn btn-secondary">Go Back</a>
                <div class="table-responsive">
                    <table class="table table-striped ">
                        <thead>
                            <tr>
                                <th>
                                    Image
                                </th>
                                <th>
                                    Course
                                </th>
                                <th>
                                    Description
                                </th>
                                <th>
                                    Course Features
                                </th>
                                <th>
                                    Settings
                                </th>

                            </tr>

                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    <img style="width: 150px; height: 150px; object-fit:cover" src="~/img/course/@Model.ImageUrl" a />
                                </td>
                                <td>
                                    <h5>@Model.Name</h5>
                                </td>
                                <td>
                                    <!-- Button trigger modal -->
                                    <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#exampleModalLong-@Model.Id">
                                        Click for Description
                                    </button>

                                    <!-- Modal -->
                                    <div class="modal fade" id="exampleModalLong-@Model.Id" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle-@Model.Id" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <h3>Description</h3>
                                                    <p>@Model.Description</p>
                                                    <div class="course-details-left">
                                                        <div class="single-course-left">
                                                            <h3>about course</h3>
                                                            <p>@Model.DetailCourse.AboutCourse</p>
                                                        </div>
                                                        <div class="single-course-left">
                                                            <h3>how to apply</h3>
                                                            <p>@Model.DetailCourse.HowToApply</p>
                                                        </div>
                                                        <div class="single-course-left">
                                                            <h3>certification</h3>
                                                            @Html.Raw(Model.DetailCourse.Certifcation)
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                    <button type="button" class="btn btn-primary">Save changes</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <!-- Button trigger modal -->
                                    <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#exampleModalLong-1">
                                        Course Features
                                    </button>

                                    <!-- Modal -->
                                    <div class="modal fade" id="exampleModalLong-1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle3-1" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <div class="course-details-right">
                                                        <h3>COURSE FEATURES</h3>
                                                        <ul>
                                                            <li>starts: <span>@Model.DetailCourse.Starts</span></li>
                                                            <li>duration: <span>@Model.DetailCourse.Duration</span></li>
                                                            <li>class duration: <span>@Model.DetailCourse.ClassDuration</span></li>
                                                            <li>skill level: <span>@Model.DetailCourse.SkilLevel</span></li>
                                                            <li>language: <span>@Model.DetailCourse.Language</span></li>
                                                            <li>students: <span>@Model.DetailCourse.Students</span></li>
                                                            <li>assesments: <span>@Model.DetailCourse.Assesment</span></li>
                                                        </ul>
                                                        <h3 class="red">course fee $@Model.DetailCourse.Price</h3>
                                                    </div>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                    <button type="button" class="btn btn-primary">Save changes</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <a class="btn btn-warning" asp-action="Update" asp-route-id="@Model.Id">
                                        Edit
                                    </a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

BackEndProject/Areas/Admin/Views/CourseAdmin/Index.cshtml
@model List<Course>
@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Course</h4>
                <a asp-controller="CourseAdmin" asp-action="Create" class="btn btn-success">Create</a>
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>
                                    Image
                                </th>
                                <th>
                                    Course
                                </th>
                                <th>
                                    Starts
                                </th>
                                <th>
                                    Language
                                </th>
                                <th>
                                    Students
                                </th>
                                <th>
                                    Price
                                </th>

                                <th>
                                    IDeleted
                                </th>
                                <th>
                                    Settings
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (Course cr in Model)
                            {

                            <tr>
                                <td>
                                    <img src="~/img/course/@cr.ImageUrl" style="width:120px; height:115px; object-fit:cover" />
                                </td>
                                <td>
                                    @cr.Name
                                </td>
                                <td>
                                    @cr.DetailCourse.Starts
                                </td>
                                <td>
                                    @cr.DetailCourse.Language
                                </td>
                                <td>
                                    @cr.DetailCourse.Students
                                </td>
                                <td>
                                    @cr.DetailCourse.Price
                                </td>
                                @if (cr.IsDeleted)
                                {
                                    <td class="text-success">
                                        Active
                                    </td>
                                }
                                else
                                {

                                    <td class="text-danger">
                                        Deactive
                                    </td>

                                }
                                <td>
                                    <a class="btn btn-info" asp-action="Detail" asp-route-id="@cr.Id">
                                        <i class="mdi mdi-account-card-details"></i>
                                    </a>
                                    <a class="btn btn-warning" asp-action="Update" asp-route-id="@cr.Id">

                                        <i class="mdi mdi-table-edit"></i>
                                    </a>
                                    @if (cr.IsDeleted)
                                    {
                                        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@cr.Id">
                                            <i class="mdi mdi-delete-sweep"></i>
                                        </a>
                                    }
                                    else
                                    {
                                        <a class="btn btn-success" asp-action="Delete" asp-route-id="@cr.Id">
                                            <i class="mdi mdi-delete-sweep"></i>
                                        </a>
                                    }

                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>